### ISSUE TITLE
Webhook URL step missing in your blog post

### ISSUE THREAD

**Issue by joemccann** [dmitryrogozhny/where-to-flat-white#1]
You skipped the webhook URL  part.  What is the value? Where do you set it?  

How do you test it locally?

**Comment by dmitryrogozhny** [comment]
Hi Joe!

I pass the webhook URL during the bot creation: [https://github.com/dmitryrogozhny/where-to-flat-white/blob/master/WhereToFlatwhiteBot/index.js#L28](https://github.com/dmitryrogozhny/where-to-flat-white/blob/master/WhereToFlatwhiteBot/index.js#L28)

This will be the URL of the Azure function. The value for the URL is taken from the Application settings. I've created the WEBHOOK_ADDRESS variable for the function to store this URL.

It'll be something like that: https://APP_NAME.azurewebsites.net/api/FUNCTION_NAME

**As for the local testing**, I'm not sure how to test this exact scenario locally. The reason is that for the webhook scenario, Telegram calls the URL we provide for the bot when it needs data for a response. This requires the URL to be externally available (with localhost address Telegram won't be able to call our function).

To test bot functionality I'd suggest to create a separate Node.js application and run the bot there without the webhook. This will cause bot logic to pull data from Telegram and this will work locally.

**Comment by joemccann** [comment]
Thanks. I got it working. You can use ngrok to proxy it locally

**Comment by dmitryrogozhny** [comment]
Great! Thank you for the tip about ngrok.
